name: Deploy to Render

on:
  push:
    branches:
      - main  # or the branch you're deploying from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment (if applicable)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # Use the appropriate Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Render CLI
      - name: Install Render CLI
        run: |
          curl -fsSL https://cdn.render.com/cli/install.sh | bash

      # Deploy to Render
      - name: Deploy to Render
        run: render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}  # Ensure this is set in GitHub secrets
